import tkinter as tk
import random

# Create the window
window = tk.Tk()
window.title("Random Color")

# Create a label to display the random color
color_label = tk.Label(window, text="", font=("Helvetica", 32))
color_label.pack()

# Define a function to update the random color
def update_color():
    # Generate a random RGB color
    r = random.randint(0, 255)
    g = random.randint(0, 255)
    b = random.randint(0, 255)
    color = "#%02x%02x%02x" % (r, g, b)
    # Update the color label text
    color_label.config(text=color, fg=color)
    # Schedule the function to be called again in 1 second
    window.after(1000, update_color)

# Call the function for the first time
update_color()

# Run the Tkinter event loop
window.mainloop()

"""
This code will create a window with a label that displays a random color. The color will be updated every second. The color is generated by randomly selecting values for the red, green, and blue components of the color, and then formatting them as a hexadecimal string. The label text and foreground color are both set to the generated color.
"""
